---
- name: Install sudo
  shell: |
    apt-get update
    apt-get install -y sudo
  become: yes


- name: Install and Start Nginx on Localhost
  hosts: localhost
  become: yes
  become_method: sudo
  gather_facts: false

  tasks:
    - name: debug
      debug:
        msg: "hello:"

    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
      delegate_to: localhost

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes
      delegate_to: localhost



